sudo: required
services: 
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_c05cfcf8776e_key -iv $encrypted_c05cfcf8776e_iv -in travis-access.json.enc -out travis-access.json -d
  - curl https://sdk.cloud.google.com | bass > /dev/null;
  - source $HOME//google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json