sudo: required
language: python
python:
  - 3.9
services: 
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_c05cfcf8776e_key -iv $encrypted_c05cfcf8776e_iv -in travis-access.json.enc -out travis-access.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME//google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file travis-access.json
  - gcloud config set project multi-k8s-460715
  - gcloud config set compute/zone asia-south1
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
  - docker build -t mandartelitech/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true mandartelitech/react-test npm test 

deploy:
  provider: script
  script: bash ./deploy.sh


